### ISSUE TITLE
Invalid lzo.decompress arg length & LZO header

### ISSUE THREAD

**Issue by rmelgares** [nlitsme/ubidump#1]
Ran into some issues on Ubuntu 16.04.3 LTS and python-lzo (1.08-1):
```
$ python2.7 ubidump.py -s test/ test.ubi --verbose
==> test.ubi <==
1 named volumes found, 2 physical volumes, blocksize=0x20000
===== block =====
EC: magic=UBI#, v1, ec=0, vidhdr=800, data=1000, imgseq=24cfe7e9  VID: magic=UBI!, v1, vt=1, cp=0, compat=5, volid=7fffefff, lnum=[0], dsize=0, usedebs=0, datapad=0, datacrc=0, sqnum=0
  VREC: rsvpebs=826, align=1, datapad=0, voltype=1, updmark=0, flags=1, name=rootfs
volume 0 : 588 lebs
volume 7fffefff : 2 lebs
== volume rootfs ==
*** superblock ***
SUPER: kh:0, fmt:0, flags=4, minio=2048, lebsize=0x1f000, lebcount=588, maxleb=2047, maxbud=8388608, loglebs=5, lptlebs=2, orphlebs=1, jheads=1, fanout=8, lsave=256, fmt=v4, compr=1, rp=0:0, rpsize=0, timegran=1000000000, uuid=a8c44348f43d4c059429b3348700911e, rocompat=0
*** masterblock ***
MST: max_inum=03760, cmtno=0, flags=2, loglnum=3, root=[587:0x0f420], rootlen=68, gc_lnum=[577], ihead=[587:0x0f800], ixsize=1204736, total(free:356352, dirty:474928, used:71229136, dead:448768, dark:146832), lpt=[08:0x00c05], nhead=[08:0x01000], ltab=[08:0x00c11], lsave=[00:0x00000], lscan=[11], empty=1, idx=10, nleb=588
ERROR function takes exactly 1 argument (3 given)
Traceback (most recent call last):
  File "ubidump.py", line 942, in main
    processfile(fn, args)
  File "ubidump.py", line 902, in processfile
    fs.savefile(inum, fh, os.path.join(path))
  File "ubidump.py", line 807, in savefile
    dat = c.getnode()
  File "ubidump.py", line 730, in getnode
    return self.fs.readnode(page.branches[ix].lnum, page.branches[ix].offs)
  File "ubidump.py", line 649, in readnode
    node.parse(nodedata)
  File "ubidump.py", line 337, in parse
    self.data = decompress(data[self.hdrsize:], self.size, self.compr_type)
  File "ubidump.py", line 289, in decompress
    return unlzo(data, buflen)
  File "ubidump.py", line 281, in unlzo
    return lzo.decompress(data, False, buflen)
TypeError: function takes exactly 1 argument (3 given)
```

Seemed that “lzo.decompress” expected one argument, so I removed the two additional parameters, and got the following error:
```
$ python2.7 ubidump.py -s test/ test.ubi --verbose
==> test.ubi <==
1 named volumes found, 2 physical volumes, blocksize=0x20000
===== block =====
EC: magic=UBI#, v1, ec=0, vidhdr=800, data=1000, imgseq=24cfe7e9  VID: magic=UBI!, v1, vt=1, cp=0, compat=5, volid=7fffefff, lnum=[0], dsize=0, usedebs=0, datapad=0, datacrc=0, sqnum=0
  VREC: rsvpebs=826, align=1, datapad=0, voltype=1, updmark=0, flags=1, name=rootfs
volume 0 : 588 lebs
volume 7fffefff : 2 lebs
== volume rootfs ==
*** superblock ***
SUPER: kh:0, fmt:0, flags=4, minio=2048, lebsize=0x1f000, lebcount=588, maxleb=2047, maxbud=8388608, loglebs=5, lptlebs=2, orphlebs=1, jheads=1, fanout=8, lsave=256, fmt=v4, compr=1, rp=0:0, rpsize=0, timegran=1000000000, uuid=a8c44348f43d4c059429b3348700911e, rocompat=0
*** masterblock ***
MST: max_inum=03760, cmtno=0, flags=2, loglnum=3, root=[587:0x0f420], rootlen=68, gc_lnum=[577], ihead=[587:0x0f800], ixsize=1204736, total(free:356352, dirty:474928, used:71229136, dead:448768, dark:146832), lpt=[08:0x00c05], nhead=[08:0x01000], ltab=[08:0x00c11], lsave=[00:0x00000], lscan=[11], empty=1, idx=10, nleb=588
ERROR Header error - invalid compressed data
Traceback (most recent call last):
  File "ubidump.py", line 943, in main
    processfile(fn, args)
  File "ubidump.py", line 903, in processfile
    fs.savefile(inum, fh, os.path.join(path))
  File "ubidump.py", line 808, in savefile
    dat = c.getnode()
  File "ubidump.py", line 731, in getnode
    return self.fs.readnode(page.branches[ix].lnum, page.branches[ix].offs)
  File "ubidump.py", line 650, in readnode
    node.parse(nodedata)
  File "ubidump.py", line 338, in parse
    self.data = decompress(data[self.hdrsize:], self.size, self.compr_type)
  File "ubidump.py", line 290, in decompress
    return unlzo(data, buflen)
  File "ubidump.py", line 279, in unlzo
    return lzo.decompress(data)
error: Header error - invalid compressed data
```

Some research led me to this: https://irdataaddict.wordpress.com/2015/03/17/python-lzo/. Apparently “lzo.decompress” freaks out if no valid LZO header is present (need to confirm that buflen is the equivalent of the decompressed_size):
```
def unlzo(data, buflen):
    header = '\xf0' + pack('>I', buflen)
    return lzo.decompress(header + data)
```

I’m then able to perform what appears to be a proper extraction:
```
$ python2.7 ../ubidump.py -s extract/ test.ubi --verbose
==> test.ubi <==
1 named volumes found, 2 physical volumes, blocksize=0x20000
===== block =====
EC: magic=UBI#, v1, ec=1, vidhdr=800, data=1000, imgseq=78377008  VID: magic=UBI!, v1, vt=1, cp=0, compat=5, volid=7fffefff, lnum=[0], dsize=0, usedebs=0, datapad=0, datacrc=0, sqnum=2
  VREC: rsvpebs=1105, align=1, datapad=0, voltype=1, updmark=0, flags=0, name=rootfs
volume 0 : 583 lebs
volume 7fffefff : 2 lebs
== volume rootfs ==
*** superblock ***
SUPER: kh:0, fmt:0, flags=4, minio=2048, lebsize=0x1f000, lebcount=556, maxleb=2047, maxbud=8388608, loglebs=5, lptlebs=2, orphlebs=1, jheads=1, fanout=8, lsave=256, fmt=v4, compr=1, rp=0:0, rpsize=0, timegran=1000000000, uuid=ad06b37975ab4dccb012abc6cc7f58eb, rocompat=0
*** masterblock ***
MST: max_inum=03614, cmtno=0, flags=2, loglnum=3, root=[555:0x1e3b8], rootlen=68, gc_lnum=[546], ihead=[555:0x1e800], ixsize=1139120, total(free:339968, dirty:441824, used:67281008, dead:413928, dark:185792), lpt=[08:0x00b59], nhead=[08:0x01000], ltab=[08:0x00b65], lsave=[00:0x00000], lscan=[11], empty=1, idx=9, nleb=556
saved 2404 files
```

**Comment by nlitsme** [comment]
That is what the `False` argument is supposed to tell the `lzo` module.

Maybe you are using an outdated version of `python-lzo`.
I am using the one from https://github.com/jd-boyd/python-lzo
