### ISSUE TITLE
The save (-s, --savedir) option does not work

### ISSUE THREAD

**Issue by shefft** [nlitsme/ubidump#2]
python ubidump.py -s rfs file.ubi
==> file.ubi <==
1 named volumes found, 2 physical volumes, blocksize=0x20000
== volume rootfs ==
ERROR function takes exactly 1 argument (3 given)

Here's the traceback with verbose mode on:
Traceback (most recent call last):
  File "ubidump.py", line 939, in main
    processfile(fn, args)
  File "ubidump.py", line 899, in processfile
    fs.savefile(inum, fh, os.path.join(path))
  File "ubidump.py", line 804, in savefile
    dat = c.getnode()
  File "ubidump.py", line 727, in getnode
    return self.fs.readnode(page.branches[ix].lnum, page.branches[ix].offs)
  File "ubidump.py", line 646, in readnode
    node.parse(nodedata)
  File "ubidump.py", line 334, in parse
    self.data = decompress(data[self.hdrsize:], self.size, self.compr_type)
  File "ubidump.py", line 286, in decompress
    return unlzo(data, buflen)
  File "ubidump.py", line 278, in unlzo
    return lzo.decompress(data, False, buflen)
TypeError: function takes exactly 1 argument (3 given)

**Comment by nlitsme** [comment]
See  #1  - you are using the wrong version of python-lzo.

Let me know if that solves your problem.

**Comment by nlitsme** [comment]
I have added code to make ubidump complain explicitly when the wrong lzo module is installed.
