### ISSUE TITLE
ERROR volume does not contain lnum

### ISSUE THREAD

**Issue by aboulfad** [nlitsme/ubidump#7]
Hello,
trying to list contents of a [UBI image](https://www.dropbox.com/s/uyckn67aysfvocv/mtdb4?dl=0) and get the following error. I am not sure I follow entirely your code but I discovered that **volid** in this line when 0 throws an exception, while in the linked ubi image, the valid volume is in entry [1] in vtbl. Thank you! https://github.com/nlitsme/ubidump/blob/d3c9b2fe8f30212a65fc22473117839fadc08c52/ubidump.py#L947

> ubidump -v -l mtdb4.bin 
> ==> mtdb4.bin <==
> 1 named volumes found, 2 physical volumes, blocksize=0x20000
> ===== block =====
> EC: magic=UBI#, v1, ec=0, vidhdr=800, data=1000, imgseq=6d52bfe2  VID: magic=UBI!, v1, vt=1, cp=0, compat=5, volid=7fffefff, lnum=[0], dsize=0, usedebs=0, datapad=0, datacrc=0, sqnum=1
>   VREC: rsvpebs=3057, align=1, datapad=0, voltype=1, updmark=0, flags=0, name=app_fs
> volume 1 : 962 lebs
> volume 7fffefff : 2 lebs
> == volume  ==
> ERROR volume does not contain lnum

> Traceback (most recent call last):
>   File "ubidump", line 1025, in main
>     processfile(fn, args)
>   File "ubidump", line 954, in processfile
>     fs = UbiFs(vol)
>   File "ubidump", line 675, in __init__
>     self.load()
>   File "ubidump", line 687, in load
>     self.sb = self.readnode(0, 0)
>   File "ubidump", line 704, in readnode
>     hdrdata = self.vol.read(lnum, offs, ch.hdrsize)
>   File "ubidump", line 181, in read
>     return self.blks.readvolume(self.volid, lnum, self.dataofs+offs, size)
>   File "ubidump", line 300, in readvolume
>     raise Exception("volume does not contain lnum")
> Exception: volume does not contain lnum

**Comment by aboulfad** [comment]
I confirmed it is an issue, I hardcoded **volid** to 1, and the tool extracted the data.

**Comment by nlitsme** [comment]
I fixed this in my latest commit  https://github.com/nlitsme/ubidump/commit/70b491410ac31022265cef4aed22847b81ada3b4
